version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get install python-pip
            sudo pip install django flake8
      - run:
          name: migrate
          command: |
            python manage.py migrate
      - run:
          name: run tests
          command: |
            python manage.py test
            flake8 --exclude polls/migrations/,manage.py  .
      - store_artifacts:
          path: test-reports
          destination: test-reports