version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get install python-pip
            sudo pip install -r requirements.txt
      - run:
          name: migrate
          command: |
            python manage.py migrate
      - run:
          name: run tests
          command: |
            python manage.py collectstatic
            python manage.py test
            flake8 --exclude polls/migrations/,manage.py  .
      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "8c:6e:5d:d2:7e:ed:5b:e9:0e:05:1b:ee:f2:c4:c4:5c"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master -f
            fi